spring:
  application:
    name: shorten-url-service
  profiles:
    active: local
  mvc:
    static-path-pattern: /ui/**

database:
  address: no-database

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}


url:
  ttl-days: 30 # URL 기한 만료 (일)
  expiration-cron: "0 0 * * * *" # 매 시간 정각 실행


rate-limit:
  requests-per-minute: 10