spring:
  application:
    name: shorten-url-service
  profiles:
    active: dev
  mvc:
    static-path-pattern: /ui/**

database:
  address: no-database

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}