@baseUrl = http://localhost:8080

### 단축 URL 생성
POST {{baseUrl}}/shortenUrl
Content-Type: application/json

{
  "originalUrl": "https://www.inflearn.com"
}

### 단축 URL 리다이렉트
GET {{baseUrl}}/SbLazPqz

### 단축 URL 정보 조회
GET {{baseUrl}}/shortenUrl/SbLazPqz

### 전체 URL 정보 조회
GET {{baseUrl}}/shortenUrls