@baseUrl = http://localhost:8080

### 단축 URL 생성
POST {{baseUrl}}/shortenUrl
Content-Type: application/json

{
  "originalUrl": "https://www.google.com"
}

### 단축 URL 리다이렉트
GET {{baseUrl}}/FcguS5dh

### 단축 URL 정보 조회
GET {{baseUrl}}/shortenUrl/FcguS5dh