name: shorten-url-observability

services:
  prometheus:
    image: prom/prometheus:v3.11.2
    container_name: shorten-url-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - shorten-url-net

  grafana:
    image: grafana/grafana:12.4.2
    container_name: shorten-url-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - shorten-url-net

  loki:
    image: grafana/loki:3.7.1
    container_name: shorten-url-loki
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki
    networks:
      - shorten-url-net

networks:
  shorten-url-net:
    name: shorten-url-net
    driver: bridge

volumes:
  grafana-data:
  loki-data: